from pathlib import Path
import base64
import shutil
import time

PROJECT = Path(r"C:\Users\Shadow\Desktop\app\AudioVidoLivingCity")
AGENT = Path(r"C:\Users\Shadow\Desktop\Unreal-Agent")
PLUGIN = PROJECT / "Plugins" / "UnrealAgentBridge" / "Source" / "UnrealAgentBridge"

H = PLUGIN / "Public" / "UnrealAgentBlueprintLibrary.h"
CPP = PLUGIN / "Private" / "UnrealAgentBlueprintLibrary.cpp"
BRIDGE = AGENT / "tools" / "unreal" / "unreal_bridge.py"
API = AGENT / "app" / "api.py"

for p in (H, CPP, BRIDGE, API):
    if not p.exists():
        raise RuntimeError("Required file missing: " + str(p))

stamp = time.strftime("%Y%m%d_%H%M%S")
backup = AGENT / "backups" / ("native_visual_v5_1_" + stamp)
backup.mkdir(parents=True, exist_ok=True)

for p in (H, CPP, BRIDGE, API):
    name = str(p).replace(":", "").replace("\\", "__").replace("/", "__")
    shutil.copy2(p, backup / name)

h = H.read_text(encoding="utf-8-sig")
cpp = CPP.read_text(encoding="utf-8-sig")
bridge = BRIDGE.read_text(encoding="utf-8-sig")
api = API.read_text(encoding="utf-8-sig")

header_decl = base64.b64decode("ICAgIFVGVU5DVElPTihCbHVlcHJpbnRDYWxsYWJsZSwgQ2F0ZWdvcnk9IlVucmVhbCBBZ2VudHxWaWV3cG9ydCIpCiAgICBzdGF0aWMgRlN0cmluZyBDYXB0dXJlQWN0aXZlVmlld3BvcnREZXRhaWxlZCgKICAgICAgICBjb25zdCBGU3RyaW5nJiBPdXRwdXRQYXRoCiAgICApOw==").decode("utf-8")
cpp_impl = base64.b64decode("Ym9vbCBVVW5yZWFsQWdlbnRCbHVlcHJpbnRMaWJyYXJ5OjpDYXB0dXJlQWN0aXZlVmlld3BvcnQoCiAgICBjb25zdCBGU3RyaW5nJiBPdXRwdXRQYXRoKQp7CiAgICByZXR1cm4gQ2FwdHVyZUFjdGl2ZVZpZXdwb3J0RGV0YWlsZWQoT3V0cHV0UGF0aCkuU3RhcnRzV2l0aChURVhUKCJPS3wiKSk7Cn0KCkZTdHJpbmcgVVVucmVhbEFnZW50Qmx1ZXByaW50TGlicmFyeTo6Q2FwdHVyZUFjdGl2ZVZpZXdwb3J0RGV0YWlsZWQoCiAgICBjb25zdCBGU3RyaW5nJiBPdXRwdXRQYXRoKQp7CiNpZiBXSVRIX0VESVRPUgogICAgaWYgKCFHRWRpdG9yKQogICAgewogICAgICAgIHJldHVybiBURVhUKCJFUlJPUnxHRWRpdG9yPW51bGwiKTsKICAgIH0KCiAgICBzdHJ1Y3QgRkNhcHR1cmVDYW5kaWRhdGUKICAgIHsKICAgICAgICBGVmlld3BvcnQqIFZpZXdwb3J0ID0gbnVsbHB0cjsKICAgICAgICBGU3RyaW5nIExhYmVsOwogICAgICAgIGludDY0IFNjb3JlID0gMDsKICAgICAgICBGSW50UG9pbnQgU2l6ZSA9IEZJbnRQb2ludDo6WmVyb1ZhbHVlOwogICAgfTsKCiAgICBUQXJyYXk8RkNhcHR1cmVDYW5kaWRhdGU+IENhbmRpZGF0ZXM7CiAgICBUU2V0PEZWaWV3cG9ydCo+IFNlZW47CgogICAgYXV0byBBZGRDYW5kaWRhdGUgPSBbJkNhbmRpZGF0ZXMsICZTZWVuXSgKICAgICAgICBGVmlld3BvcnQqIEluVmlld3BvcnQsCiAgICAgICAgY29uc3QgRlN0cmluZyYgSW5MYWJlbCwKICAgICAgICBpbnQ2NCBCb251cykKICAgIHsKICAgICAgICBpZiAoIUluVmlld3BvcnQgfHwgU2Vlbi5Db250YWlucyhJblZpZXdwb3J0KSkKICAgICAgICB7CiAgICAgICAgICAgIHJldHVybjsKICAgICAgICB9CgogICAgICAgIFNlZW4uQWRkKEluVmlld3BvcnQpOwoKICAgICAgICBGSW50UG9pbnQgU2l6ZSA9IEluVmlld3BvcnQtPkdldFJlbmRlclRhcmdldFRleHR1cmVTaXplWFkoKTsKCiAgICAgICAgaWYgKFNpemUuWCA8PSAwIHx8IFNpemUuWSA8PSAwKQogICAgICAgIHsKICAgICAgICAgICAgU2l6ZSA9IEluVmlld3BvcnQtPkdldFNpemVYWSgpOwogICAgICAgIH0KCiAgICAgICAgaWYgKFNpemUuWCA8PSAwIHx8IFNpemUuWSA8PSAwKQogICAgICAgIHsKICAgICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KCiAgICAgICAgRkNhcHR1cmVDYW5kaWRhdGUgQ2FuZGlkYXRlOwogICAgICAgIENhbmRpZGF0ZS5WaWV3cG9ydCA9IEluVmlld3BvcnQ7CiAgICAgICAgQ2FuZGlkYXRlLkxhYmVsID0gSW5MYWJlbDsKICAgICAgICBDYW5kaWRhdGUuU2l6ZSA9IFNpemU7CiAgICAgICAgQ2FuZGlkYXRlLlNjb3JlID0KICAgICAgICAgICAgQm9udXMgKwogICAgICAgICAgICAoc3RhdGljX2Nhc3Q8aW50NjQ+KFNpemUuWCkgKiBzdGF0aWNfY2FzdDxpbnQ2ND4oU2l6ZS5ZKSk7CgogICAgICAgIENhbmRpZGF0ZXMuQWRkKE1vdmVUZW1wKENhbmRpZGF0ZSkpOwogICAgfTsKCiAgICBjb25zdCBUQXJyYXk8RkxldmVsRWRpdG9yVmlld3BvcnRDbGllbnQqPiYgTGV2ZWxDbGllbnRzID0KICAgICAgICBHRWRpdG9yLT5HZXRMZXZlbFZpZXdwb3J0Q2xpZW50cygpOwoKICAgIGZvciAoaW50MzIgSW5kZXggPSAwOyBJbmRleCA8IExldmVsQ2xpZW50cy5OdW0oKTsgKytJbmRleCkKICAgIHsKICAgICAgICBGTGV2ZWxFZGl0b3JWaWV3cG9ydENsaWVudCogQ2xpZW50ID0gTGV2ZWxDbGllbnRzW0luZGV4XTsKCiAgICAgICAgaWYgKCFDbGllbnQgfHwgIUNsaWVudC0+Vmlld3BvcnQpCiAgICAgICAgewogICAgICAgICAgICBjb250aW51ZTsKICAgICAgICB9CgogICAgICAgIGludDY0IEJvbnVzID0gMDsKCiAgICAgICAgaWYgKENsaWVudC0+SXNQZXJzcGVjdGl2ZSgpKQogICAgICAgIHsKICAgICAgICAgICAgQm9udXMgKz0gMTAwMDAwMDAwMDAwMExMOwogICAgICAgIH0KCiAgICAgICAgaWYgKENsaWVudC0+SXNWaXNpYmxlKCkpCiAgICAgICAgewogICAgICAgICAgICBCb251cyArPSAxMDAwMDAwMDAwMDBMTDsKICAgICAgICB9CgogICAgICAgIEFkZENhbmRpZGF0ZSgKICAgICAgICAgICAgQ2xpZW50LT5WaWV3cG9ydCwKICAgICAgICAgICAgRlN0cmluZzo6UHJpbnRmKAogICAgICAgICAgICAgICAgVEVYVCgiTGV2ZWxWaWV3cG9ydFslZF18cGVyc3BlY3RpdmU9JWR8dmlzaWJsZT0lZCIpLAogICAgICAgICAgICAgICAgSW5kZXgsCiAgICAgICAgICAgICAgICBDbGllbnQtPklzUGVyc3BlY3RpdmUoKSA/IDEgOiAwLAogICAgICAgICAgICAgICAgQ2xpZW50LT5Jc1Zpc2libGUoKSA/IDEgOiAwCiAgICAgICAgICAgICksCiAgICAgICAgICAgIEJvbnVzCiAgICAgICAgKTsKICAgIH0KCiAgICBBZGRDYW5kaWRhdGUoCiAgICAgICAgR0VkaXRvci0+R2V0QWN0aXZlVmlld3BvcnQoKSwKICAgICAgICBURVhUKCJHRWRpdG9yQWN0aXZlVmlld3BvcnQiKSwKICAgICAgICAxMDAwMDAwMDAwMExMCiAgICApOwoKICAgIENhbmRpZGF0ZXMuU29ydCgKICAgICAgICBbXShjb25zdCBGQ2FwdHVyZUNhbmRpZGF0ZSYgQSwgY29uc3QgRkNhcHR1cmVDYW5kaWRhdGUmIEIpCiAgICAgICAgewogICAgICAgICAgICByZXR1cm4gQS5TY29yZSA+IEIuU2NvcmU7CiAgICAgICAgfQogICAgKTsKCiAgICBpZiAoQ2FuZGlkYXRlcy5OdW0oKSA9PSAwKQogICAgewogICAgICAgIHJldHVybiBGU3RyaW5nOjpQcmludGYoCiAgICAgICAgICAgIFRFWFQoIkVSUk9SfG5vX3ZhbGlkX3ZpZXdwb3J0fGxldmVsX2NsaWVudHM9JWQiKSwKICAgICAgICAgICAgTGV2ZWxDbGllbnRzLk51bSgpCiAgICAgICAgKTsKICAgIH0KCiAgICBGU3RyaW5nIEZpbmFsUGF0aCA9IE91dHB1dFBhdGg7CgogICAgaWYgKEZpbmFsUGF0aC5Jc0VtcHR5KCkpCiAgICB7CiAgICAgICAgRmluYWxQYXRoID0gRlBhdGhzOjpDb21iaW5lKAogICAgICAgICAgICBGUGF0aHM6OlByb2plY3RTYXZlZERpcigpLAogICAgICAgICAgICBURVhUKCJVbnJlYWxBZ2VudCIpLAogICAgICAgICAgICBURVhUKCJ2aWV3cG9ydF9sYXRlc3QucG5nIikKICAgICAgICApOwogICAgfQoKICAgIGlmIChGUGF0aHM6OkdldEV4dGVuc2lvbihGaW5hbFBhdGgpLklzRW1wdHkoKSkKICAgIHsKICAgICAgICBGaW5hbFBhdGggKz0gVEVYVCgiLnBuZyIpOwogICAgfQoKICAgIGNvbnN0IEZTdHJpbmcgT3V0cHV0RGlyZWN0b3J5ID0gRlBhdGhzOjpHZXRQYXRoKEZpbmFsUGF0aCk7CgogICAgaWYgKCFPdXRwdXREaXJlY3RvcnkuSXNFbXB0eSgpKQogICAgewogICAgICAgIElGaWxlTWFuYWdlcjo6R2V0KCkuTWFrZURpcmVjdG9yeSgKICAgICAgICAgICAgKk91dHB1dERpcmVjdG9yeSwKICAgICAgICAgICAgdHJ1ZQogICAgICAgICk7CiAgICB9CgogICAgRlN0cmluZyBMYXN0RmFpbHVyZSA9IFRFWFQoIm5vbmUiKTsKCiAgICBmb3IgKGNvbnN0IEZDYXB0dXJlQ2FuZGlkYXRlJiBDYW5kaWRhdGUgOiBDYW5kaWRhdGVzKQogICAgewogICAgICAgIGlmICghQ2FuZGlkYXRlLlZpZXdwb3J0KQogICAgICAgIHsKICAgICAgICAgICAgY29udGludWU7CiAgICAgICAgfQoKICAgICAgICBUQXJyYXk8RkNvbG9yPiBQaXhlbHM7CgogICAgICAgIEZSZWFkU3VyZmFjZURhdGFGbGFncyBSZWFkRmxhZ3MoUkNNX1VOb3JtKTsKICAgICAgICBSZWFkRmxhZ3MuU2V0TGluZWFyVG9HYW1tYSh0cnVlKTsKCiAgICAgICAgY29uc3QgRkludFJlY3QgU291cmNlUmVjdCgKICAgICAgICAgICAgMCwKICAgICAgICAgICAgMCwKICAgICAgICAgICAgQ2FuZGlkYXRlLlNpemUuWCwKICAgICAgICAgICAgQ2FuZGlkYXRlLlNpemUuWQogICAgICAgICk7CgogICAgICAgIGNvbnN0IGJvb2wgYlJlYWQgPSBDYW5kaWRhdGUuVmlld3BvcnQtPlJlYWRQaXhlbHMoCiAgICAgICAgICAgIFBpeGVscywKICAgICAgICAgICAgUmVhZEZsYWdzLAogICAgICAgICAgICBTb3VyY2VSZWN0CiAgICAgICAgKTsKCiAgICAgICAgaWYgKCFiUmVhZCkKICAgICAgICB7CiAgICAgICAgICAgIExhc3RGYWlsdXJlID0gRlN0cmluZzo6UHJpbnRmKAogICAgICAgICAgICAgICAgVEVYVCgicmVhZHBpeGVsc19mYWlsZWR8c291cmNlPSVzfHdpZHRoPSVkfGhlaWdodD0lZCIpLAogICAgICAgICAgICAgICAgKkNhbmRpZGF0ZS5MYWJlbCwKICAgICAgICAgICAgICAgIENhbmRpZGF0ZS5TaXplLlgsCiAgICAgICAgICAgICAgICBDYW5kaWRhdGUuU2l6ZS5ZCiAgICAgICAgICAgICk7CiAgICAgICAgICAgIGNvbnRpbnVlOwogICAgICAgIH0KCiAgICAgICAgaWYgKFBpeGVscy5OdW0oKSAhPSBDYW5kaWRhdGUuU2l6ZS5YICogQ2FuZGlkYXRlLlNpemUuWSkKICAgICAgICB7CiAgICAgICAgICAgIExhc3RGYWlsdXJlID0gRlN0cmluZzo6UHJpbnRmKAogICAgICAgICAgICAgICAgVEVYVCgicGl4ZWxfY291bnRfbWlzbWF0Y2h8c291cmNlPSVzfGdvdD0lZHxleHBlY3RlZD0lZCIpLAogICAgICAgICAgICAgICAgKkNhbmRpZGF0ZS5MYWJlbCwKICAgICAgICAgICAgICAgIFBpeGVscy5OdW0oKSwKICAgICAgICAgICAgICAgIENhbmRpZGF0ZS5TaXplLlggKiBDYW5kaWRhdGUuU2l6ZS5ZCiAgICAgICAgICAgICk7CiAgICAgICAgICAgIGNvbnRpbnVlOwogICAgICAgIH0KCiAgICAgICAgZm9yIChGQ29sb3ImIFBpeGVsIDogUGl4ZWxzKQogICAgICAgIHsKICAgICAgICAgICAgUGl4ZWwuQSA9IDI1NTsKICAgICAgICB9CgogICAgICAgIGNvbnN0IEZJbWFnZVZpZXcgSW1hZ2VWaWV3KAogICAgICAgICAgICBQaXhlbHMuR2V0RGF0YSgpLAogICAgICAgICAgICBDYW5kaWRhdGUuU2l6ZS5YLAogICAgICAgICAgICBDYW5kaWRhdGUuU2l6ZS5ZLAogICAgICAgICAgICBFR2FtbWFTcGFjZTo6c1JHQgogICAgICAgICk7CgogICAgICAgIGNvbnN0IGJvb2wgYlNhdmVkID0gRkltYWdlVXRpbHM6OlNhdmVJbWFnZUJ5RXh0ZW5zaW9uKAogICAgICAgICAgICAqRmluYWxQYXRoLAogICAgICAgICAgICBJbWFnZVZpZXcsCiAgICAgICAgICAgIDEwMAogICAgICAgICk7CgogICAgICAgIGlmICghYlNhdmVkKQogICAgICAgIHsKICAgICAgICAgICAgTGFzdEZhaWx1cmUgPSBGU3RyaW5nOjpQcmludGYoCiAgICAgICAgICAgICAgICBURVhUKCJzYXZlX2ZhaWxlZHxzb3VyY2U9JXN8cGF0aD0lcyIpLAogICAgICAgICAgICAgICAgKkNhbmRpZGF0ZS5MYWJlbCwKICAgICAgICAgICAgICAgICpGaW5hbFBhdGgKICAgICAgICAgICAgKTsKICAgICAgICAgICAgY29udGludWU7CiAgICAgICAgfQoKICAgICAgICBjb25zdCBpbnQ2NCBGaWxlU2l6ZSA9IElGaWxlTWFuYWdlcjo6R2V0KCkuRmlsZVNpemUoKkZpbmFsUGF0aCk7CgogICAgICAgIGlmIChGaWxlU2l6ZSA8PSAwKQogICAgICAgIHsKICAgICAgICAgICAgTGFzdEZhaWx1cmUgPSBGU3RyaW5nOjpQcmludGYoCiAgICAgICAgICAgICAgICBURVhUKCJmaWxlX2VtcHR5fHNvdXJjZT0lc3xwYXRoPSVzIiksCiAgICAgICAgICAgICAgICAqQ2FuZGlkYXRlLkxhYmVsLAogICAgICAgICAgICAgICAgKkZpbmFsUGF0aAogICAgICAgICAgICApOwogICAgICAgICAgICBjb250aW51ZTsKICAgICAgICB9CgogICAgICAgIHJldHVybiBGU3RyaW5nOjpQcmludGYoCiAgICAgICAgICAgIFRFWFQoIk9LfHNvdXJjZT0lc3x3aWR0aD0lZHxoZWlnaHQ9JWR8Ynl0ZXM9JWxsZHxwYXRoPSVzIiksCiAgICAgICAgICAgICpDYW5kaWRhdGUuTGFiZWwsCiAgICAgICAgICAgIENhbmRpZGF0ZS5TaXplLlgsCiAgICAgICAgICAgIENhbmRpZGF0ZS5TaXplLlksCiAgICAgICAgICAgIHN0YXRpY19jYXN0PGxvbmcgbG9uZz4oRmlsZVNpemUpLAogICAgICAgICAgICAqRmluYWxQYXRoCiAgICAgICAgKTsKICAgIH0KCiAgICByZXR1cm4gRlN0cmluZzo6UHJpbnRmKAogICAgICAgIFRFWFQoIkVSUk9SfGNhbmRpZGF0ZXM9JWR8bGFzdD0lcyIpLAogICAgICAgIENhbmRpZGF0ZXMuTnVtKCksCiAgICAgICAgKkxhc3RGYWlsdXJlCiAgICApOwojZWxzZQogICAgcmV0dXJuIFRFWFQoIkVSUk9SfG5vdF9lZGl0b3IiKTsKI2VuZGlmCn0=").decode("utf-8")
bridge_method = base64.b64decode("ICAgIGRlZiBjYXB0dXJlX3VucmVhbF92aWV3cG9ydChzZWxmKToKICAgICAgICByZXR1cm4gc2VsZi5leGVjdXRlX3B5dGhvbihyIiIiCmltcG9ydCBvcwoKc2F2ZWRfZGlyID0gdW5yZWFsLlBhdGhzLmNvbnZlcnRfcmVsYXRpdmVfcGF0aF90b19mdWxsKAogICAgdW5yZWFsLlBhdGhzLnByb2plY3Rfc2F2ZWRfZGlyKCkKKQoKb3V0X2RpciA9IG9zLnBhdGguam9pbigKICAgIHNhdmVkX2RpciwKICAgICJVbnJlYWxBZ2VudCIKKQoKb3MubWFrZWRpcnMob3V0X2RpciwgZXhpc3Rfb2s9VHJ1ZSkKCnBhdGggPSBvcy5wYXRoLmpvaW4oCiAgICBvdXRfZGlyLAogICAgInZpZXdwb3J0X2xhdGVzdC5wbmciCikKCmRpYWdub3N0aWMgPSAoCiAgICB1bnJlYWwuVW5yZWFsQWdlbnRCbHVlcHJpbnRMaWJyYXJ5CiAgICAuY2FwdHVyZV9hY3RpdmVfdmlld3BvcnRfZGV0YWlsZWQocGF0aCkKKQoKZGlhZ25vc3RpYyA9IHN0cihkaWFnbm9zdGljKQpvayA9IGRpYWdub3N0aWMuc3RhcnRzd2l0aCgiT0t8IikKCnNpemUgPSAwCgp0cnk6CiAgICBpZiBvcy5wYXRoLmlzZmlsZShwYXRoKToKICAgICAgICBzaXplID0gb3MucGF0aC5nZXRzaXplKHBhdGgpCmV4Y2VwdCBFeGNlcHRpb246CiAgICBzaXplID0gMAoKX19icmlkZ2VfcmVzdWx0X18gPSB7CiAgICAib2siOiBib29sKG9rKSwKICAgICJwYXRoIjogcGF0aCwKICAgICJzaXplIjogc2l6ZSwKICAgICJkaWFnbm9zdGljIjogZGlhZ25vc3RpYwp9CiIiIik=").decode("utf-8")

if "CaptureActiveViewportDetailed" not in h:
    pos = h.rfind("};")
    if pos < 0:
        raise RuntimeError("Could not find header class closing brace.")
    h = h[:pos].rstrip() + "\n\n" + header_decl + "\n" + h[pos:]

if '#include "LevelEditorViewport.h"' not in cpp:
    anchor = '#include "Editor.h"'
    if anchor in cpp:
        cpp = cpp.replace(
            anchor,
            anchor + '\n#include "LevelEditorViewport.h"',
            1
        )
    else:
        first = '#include "UnrealAgentBlueprintLibrary.h"'
        if first not in cpp:
            raise RuntimeError("Could not find CPP include insertion point.")
        cpp = cpp.replace(
            first,
            first + '\n#include "Editor.h"\n#include "LevelEditorViewport.h"',
            1
        )

start_marker = "bool UUnrealAgentBlueprintLibrary::CaptureActiveViewport("
start = cpp.find(start_marker)

if start < 0:
    raise RuntimeError("Existing CaptureActiveViewport implementation not found.")

cpp = cpp[:start].rstrip() + "\n\n" + cpp_impl + "\n"

start_marker = "    def capture_unreal_viewport(self):"
end_marker = "    def visual_review_unreal(self):"
start = bridge.find(start_marker)
end = bridge.find(end_marker, start)

if start < 0 or end < 0:
    raise RuntimeError("Could not locate bridge capture method.")

bridge = bridge[:start] + bridge_method + "\n\n" + bridge[end:]

api = api.replace('version="5.0.0"', 'version="5.1.0"', 1)
api = api.replace('"version": "Adaptive API v5"', '"version": "Adaptive API v5.1"', 1)

compile(bridge, str(BRIDGE), "exec")
compile(api, str(API), "exec")

H.write_text(h, encoding="utf-8")
CPP.write_text(cpp, encoding="utf-8")
BRIDGE.write_text(bridge, encoding="utf-8")
API.write_text(api, encoding="utf-8")

print("PATCH_V5_1_SOURCE=PASS")
print("BACKUP_DIR=" + str(backup))
