# Unreal Python Script: AividoHQ_Final_Stage Integration
# Generated by Worker 5 Final Integration

import unreal

# Create or load final staging map
editor_asset_lib = unreal.EditorAssetLibrary()
map_path = "/Game/Aivido/Production/Integration/Maps/AividoHQ_Final_Stage"

# Check if map exists, create if not
if not editor_asset_lib.does_asset_exist(map_path):
    # Create new map from default template
    empty_map = unreal.EditorAssetLibrary.load_asset("/Engine/Maps/Templates/Template_Default")
    editor_asset_lib.duplicate_asset("/Engine/Maps/Templates/Template_Default", map_path)
    print(f"Created new map: {map_path}")
else:
    print(f"Map already exists: {map_path}")

# Load the map
editor_level_lib = unreal.EditorLevelLibrary()
current_map = editor_level_lib.get_current_level_name()
if current_map != "AividoHQ_Final_Stage":
    editor_level_lib.load_level(map_path)

# Character definitions from Worker 2
characters = [
    {"id": "Master", "mesh": "/Game/AividoHQ/Characters/Master/Business_Male_01", "pos": [0, 500, 0], "rot": [0, 0, 0]},
    {"id": "Creative", "mesh": "/Game/AividoHQ/Characters/Creative/Male_Adult_11", "pos": [1200, 800, 0], "rot": [0, -45, 0]},
    {"id": "Visual", "mesh": "/Game/AividoHQ/Characters/Visual/Business_Female_02", "pos": [-1200, 800, 0], "rot": [0, 45, 0]},
    {"id": "Technical", "mesh": "/Game/AividoHQ/Characters/Technical/Male_Adult_03", "pos": [800, 200, 0], "rot": [0, 90, 0]},
    {"id": "Audio", "mesh": "/Game/AividoHQ/Characters/Audio/Female_Adult_05", "pos": [-800, 200, 0], "rot": [0, -90, 0]},
    {"id": "Animation", "mesh": "/Game/AividoHQ/Characters/Animation/Male_Adult_12", "pos": [400, 1500, 0], "rot": [0, 180, 0]},
    {"id": "Lighting", "mesh": "/Game/AividoHQ/Characters/Lighting/Female_Adult_01", "pos": [-400, 1500, 0], "rot": [0, 180, 0]},
    {"id": "VFX", "mesh": "/Game/AividoHQ/Characters/VFX/Female_Adult_08", "pos": [0, 1200, 0], "rot": [0, 0, 0]},
]

# Spawn characters
for char in characters:
    mesh_asset = unreal.EditorAssetLibrary.load_asset(char["mesh"])
    if mesh_asset:
        location = unreal.Vector(char["pos"][0], char["pos"][1], char["pos"][2])
        rotation = unreal.Rotator(char["rot"][0], char["rot"][1], char["rot"][2])
        
        actor = editor_level_lib.spawn_actor_from_object(
            mesh_asset,
            location,
            rotation
        )
        
        if actor:
            actor.set_actor_label(f"Aivido_{char['id']}")
            print(f"Spawned: {char['id']} at {location}")
        else:
            print(f"Failed to spawn: {char['id']}")
    else:
        print(f"Mesh not found: {char['mesh']}")

# Save map
editor_asset_lib.save_asset(map_path)
print(f"Map saved: {map_path}")

print("Aivido Worker 5 Integration Complete - 8 characters placed in final staging map")
